before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjson0-dev/trusty-backports libjson0/trusty-backports

before_script:
    # Compile PHP
    - ./travis/compile.sh

script: 
 - ./travis/build_check.sh

